### ISSUE TITLE
Can this be used to parse indentation-sensitive languages like Python?

### ISSUE THREAD

**Issue by theronic** [aroemers/crustimoney#13]
How should I handle indent/dedent?

**Comment by aroemers** [comment]
Hi @theronic,

Funny you found this library. While parsing indentation based languages would certainly be possible in theory, I would advise not to use crustimoney. I noticed it has some bugs and it has not been maintained. I started a rewrite some time ago, but I did not finish it yet. I advise you to use something like [Instaparse](https://github.com/Engelberg/instaparse) instead.

**Comment by theronic** [comment]
Thanks for the update. Instaparse is designed to parse context-free grammars, but indent-dependence implies context-sensitivity which, as I understand it, PEGs can handle.
