### ISSUE TITLE
Matching multiple elements?

### ISSUE THREAD

**Issue by theronic** [aroemers/crustimoney#14]
Thanks for this! I'm trying to parse a basic indent-sensitive language, but I can't figure out how to handle multiple root-level matches. E.g.:

```
node 1:
 - child 1a
 - child 1b

node 2:
 - child 2a
 - child 2b
 - child 2c (etc.)
```

How would get back a vector of root nodes, each with a vector of their child nodes?

(As I understand it, PEG parsers should be able to handle indent/outdent matching.)

**Comment by aroemers** [comment]
Hi theronic,

Thank you for your interest in this library, and sorry for my late reply. Crustimoney is not maintained at the moment. I do not have a ready answer for you, without spending time to learn my own library again :) Did you already figure it out?

**Comment by aroemers** [comment]
Hi theronic,

Almost four years later, I took on the task of rewriting the library. So to answer your question, you'd need something like:

```
grammar <- root*
root    <- name child*
child   <- ...
```

Closing this for now.
